multinode_mode: true
undercloud_user: jenkins
non_root_user: jenkins
enable_vbmc: false
gating_repo_enabled: true

tripleo_root: "{{ lookup('env','TRIPLEO_ROOT') }}"
extra_args: >
    -e /usr/share/openstack-tripleo-heat-templates/environments/deployed-server-environment.yaml
    -e ${TRIPLEO_ROOT}/tripleo-ci/test-environments/worker-config.yaml
    -e /usr/share/openstack-tripleo-heat-templates/environments/debug.yaml
    --compute-scale 0

deploy_composable_scenario: true
composable_scenario: "multinode.yaml"

ssl_overcloud: false
network_isolation: false
flavor_args: ""
undercloud_local_interface: "br-ex"
undercloud_generate_service_certificate: false
undercloud_check_idempotency: true
undercloud_check_sanity: true

toci_vxlan_networking: true
toci_vxlan_networking_multinode: true
hostname_correction: true
package_installs: true
non_root_user_setup: true

step_overcloud_image: false
step_glance_upload: true
step_register: false

hypervisor_wait: false
deployed_server: true
validation_args: "--validation-errors-nonfatal"
deploy_timeout: 30

undercloud_conf_extras: "net_config_override = /opt/stack/new/tripleo-ci/undercloud-configs/net-config-multinode.json.template"

# TODO(trown): Create repo configs for each release in the release configs
repos:
  - type: generic
    reponame: delorean
    filename: delorean.repo
    baseurl: http://buildlogs.centos.org/centos/7/cloud/x86_64/rdo-trunk-master-tripleo/
    hash_url: http://buildlogs.centos.org/centos/7/cloud/x86_64/rdo-trunk-master-tripleo/delorean.repo
    priority: 20

  - type: generic
    reponame: delorean-current
    filename: delorean-current.repo
    baseurl: http://trunk.rdoproject.org/centos7/current
    hash_url: http://trunk.rdoproject.org/centos7/current/delorean.repo
    priority: 10
    includepkgs:
      - diskimage-builder
      - instack
      - instack-undercloud
      - os-apply-config
      - os-cloud-config
      - os-collect-config
      - os-net-config
      - os-refresh-config
      - python-tripleoclient
      - openstack-tripleo-common
      - openstack-tripleo-heat-templates
      - openstack-tripleo-image-elements
      - openstack-tripleo
      - openstack-tripleo-puppet-elements
      - openstack-puppet-modules
      - openstack-tripleo-ui
      - puppet-*

  - type: file
    filename: delorean-deps.repo
    down_url: http://trunk.rdoproject.org/centos7-master/delorean-deps.repo

  - type: package
    pkg_name: centos-release-ceph-jewel
    custom_cmd: 'yum install -y --enablerepo=extras'

# TODO(sshnaidm): artcl_tar_gz should be tested before
# artcl_tar_gz: true
artcl_gzip_only: true
artcl_txt_rename: true
artcl_publish: true
artcl_rsync_logs: false
artcl_collect_list:
  - /etc/
  - /var/log/
  - /home/jenkins/.instack/install-undercloud.log
  - /home/jenkins/stackrc
  - /home/jenkins/overcloudrc
  - /home/jenkins/*.log
  - /home/jenkins/*.txt
  - /home/jenkins/*.json
  - /home/jenkins/*.conf
  - /home/jenkins/*.yml
  - /home/jenkins/*.yaml
  - /home/jenkins/*.sh
  - /home/jenkins/deploy-overcloudrc
  - /home/jenkins/network-environment.yaml
  - /home/jenkins/tempest/*.xml
  - /home/jenkins/tempest/*.html
  - /home/jenkins/tempest/*.log
  - /home/jenkins/tempest/*.sh
  - /home/jenkins/tempest/etc/*.conf
  - /home/jenkins/local_tht/
  - /usr/share/openstack-tripleo-heat-templates/
  - /tmp/*.yml
  - /tmp/*.yaml
artcl_exclude_list:
  - /etc/udev/hwdb.bin
  - /etc/puppet/modules
  - /etc/project-config
  - /etc/services
  - /etc/selinux/targeted
  - /etc/pki/ca-trust/extracted
  - /etc/alternatives
