# OVB settings
multinode_mode: false
undercloud_user: jenkins
non_root_user: jenkins
ssh_user: jenkins
enable_vbmc: false
gating_repo_enabled: true

# Undercloud setup
undercloud_ironic_ipxe_port: 3816
non_root_user_setup: false
step_set_undercloud_hostname: true
undercloud_hostname: undercloud

undercloud_generate_service_certificate: true
tempest_config: false
test_regex: '.*smoke'
ssl_overcloud: false
overcloud_templates_path: /usr/share/openstack-tripleo-heat-templates

# Overcloud deploy
overcloud_templates_path: /usr/share/openstack-tripleo-heat-templates

# Network
# Deploy args
flavor_args: ""
deploy_timeout: 110

# Images settings
image_cache_dir: "{{ working_dir }}/images-cache"
image_cache_dir_cleanup: true
images_working_dir: "{{ working_dir }}"
build_image_isolated: false
build_undercloud: false
images_destroy_working_dir: false
libguestfs_mode: false

# Network settings
step_adjust_mtu: true
mtu: 1350
external_interface: eth2
external_interface_ip: 10.0.0.1
external_interface_netmask: 255.255.255.0
external_interface_hwaddr: fa:16:3e:79:e8:04
overcloud_dns_servers:
  - 10.1.8.10
  - 8.8.8.8
  - 8.8.4.4

float_base: "{% if network_isolation|bool %}10.0.0{% else %}192.168.24{% endif %}"
floating_ip_cidr: "{{ float_base}}.0/24"
public_net_pool_start: "{{ float_base}}.150"
public_net_pool_end: "{{ float_base}}.250"
public_net_gateway: "{{ float_base}}.1"
mtu_interface:
  - eth0
  - eth1
  - eth2

# Collect logs settings

# TODO(sshnaidm): artcl_tar_gz should be tested before
# artcl_tar_gz: true
artcl_gzip_only: true
artcl_txt_rename: true
artcl_publish: true
artcl_rsync_logs: false
artcl_collect_list:
  - /etc/
  - /var/log/
  - /var/lib/pacemaker/cib/cib*
  - /home/jenkins/.instack/install-undercloud.log
  - /home/jenkins/stackrc
  - /home/jenkins/overcloudrc
  - /home/jenkins/*.log
  - /home/jenkins/*.txt
  - /home/jenkins/*.json
  - /home/jenkins/*.conf
  - /home/jenkins/*.yml
  - /home/jenkins/*.yaml
  - /home/jenkins/*.sh
  - /home/jenkins/deploy-overcloudrc
  - /home/jenkins/network-environment.yaml
  - /home/jenkins/skip_file
  - /home/jenkins/tempest/*.xml
  - /home/jenkins/tempest/*.html
  - /home/jenkins/tempest/*.log
  - /home/jenkins/tempest/*.sh
  - /home/jenkins/tempest/*.subunit
  - /home/jenkins/tempest/etc/*.conf
  - /home/jenkins/local_tht/
  - /tmp/*.yml
  - /tmp/*.yaml
artcl_exclude_list:
  - /etc/asound.conf
  - /etc/at.deny
  - /etc/bash_completion.d/
  - /etc/bashrc
  - /etc/csh*
  - /etc/dbus-1
  - /etc/dhcp
  - /etc/DIR_COLORS*
  - /etc/favicon.png
  - /etc/fonts
  - /etc/GeoIP*
  - /etc/GREP_COLORS
  - /etc/grub*
  - /etc/ld.so.conf*
  - /etc/pam*
  - /etc/postfix*
  - /etc/pulse
  - /etc/samba*
  - /etc/X11
  - /etc/xinetd*
  - /etc/udev/hwdb.bin
  - /etc/puppet/modules
  - /etc/project-config
  - /etc/services
  - /etc/selinux/targeted
  - /etc/pki/ca-trust/extracted
  - /etc/alternatives
  - /var/log/extra/lsof*
