# This file contains settings that are specific to RDO Cloud.
# These settings will override the ovb default settings

bmc_flavor: ci.m1.small
baremetal_flavor: ci.m1.xlarge
undercloud_flavor: ci.m1.xlarge

custom_nameserver:
    - 38.145.33.91
    - 38.145.32.66
    - 38.145.32.79
undercloud_undercloud_nameservers: "{{ custom_nameserver }}"
external_net: '38.145.32.0/22'
overcloud_dns_servers: "{{ custom_nameserver }}"
ntp_server: 'pool.ntp.org'
workers_args: >-
    -e {{ overcloud_templates_path }}/environments/low-memory-usage.yaml
    -e {{ tripleo_root }}/tripleo-ci/test-environments/worker-config.yaml
    -e {{ overcloud_templates_path }}/environments/debug.yaml
overcloud_image_url: http://images.rdoproject.org/{{ release }}/rdo_trunk/{{ dlrn_hash|default(dlrn_hash_tag) }}/overcloud-full.tar
ipa_image_url: http://images.rdoproject.org/{{ release }}/rdo_trunk/{{ dlrn_hash|default(dlrn_hash_tag) }}/ironic-python-agent.tar
# Container settings
# Use trunk.registry.rdoproject.org for periodic jobs only
docker_registry_host: "{% if lookup('env', 'PERIODIC')|default('0')|int != 1 %}docker.io{% else %}trunk.registry.rdoproject.org{% endif %}"
docker_registry_namespace: "{% if lookup('env', 'PERIODIC')|default('0')|int != 1 %}tripleo{% endif %}{{ release }}"

# Container update settings
update_containers: "{% if containerized_overcloud|bool %}true{% endif %}"

# We don't need to cleanup TripleO CI
tempest_track_resources: false

# Tempestmail settings
tempestmail_log_server: http://logs.rdoproject.org

#build-test packages
artg_repos_dir: "{{ tripleo_root }}"

# InfluxDB module settings
influxdb_only_successful_tasks: true
influxdb_measurement: job
influxdb_url: https://influxdb.review.rdoproject.org
influxdb_port: 8086
influxdb_user: tripleo_ci
influxdb_password:
influxdb_dbname: tripleo_ci
influxdb_data_file_path: "{{ artcl_collect_dir }}/influxdb_data"
influxdb_create_data_file: true
