undercloud_user: "{{ lookup('env','USER') }}"
non_root_user: "{{ undercloud_user }}"
ssh_user: "{{ undercloud_user }}"
enable_vbmc: false
gating_repo_enabled: true

# Undercloud setup
undercloud_ironic_ipxe_port: 3816
non_root_user_setup: false
step_set_undercloud_hostname: true
undercloud_hostname: undercloud

skip_pingtest_cleanup: true
# Overcloud deploy
overcloud_templates_path: /usr/share/openstack-tripleo-heat-templates

# Network
# Deploy args
flavor_args: ""

deploy_timeout: 110

# Images settings
image_cache_dir: "{{ working_dir }}/images-cache"
image_cache_dir_cleanup: true
images_working_dir: "{{ working_dir }}"
build_image_isolated: false
build_undercloud: false
images_destroy_working_dir: false
modify_image_extract_list:
  - /tmp/builder.log

# Without this wildcard, the deployment will fail with "no valid host found"
# since nova will try to find defined flavors in the capabilities of the node
# and nothing currently is configured to modify those.
#extra_args: " --control-flavor baremetal --compute-flavor baremetal --ceph-storage-flavor baremetal"
