undercloud_user: "{{ lookup('env','USER') }}"
non_root_user: "{{ undercloud_user }}"
ssh_user: "{{ undercloud_user }}"
enable_vbmc: false
gating_repo_enabled: true

# Undercloud setup
undercloud_ironic_ipxe_port: 3816
non_root_user_setup: false
step_set_undercloud_hostname: true
undercloud_hostname: undercloud
undercloud_docker_registry_mirror: "{{ lookup('env','NODEPOOL_DOCKER_REGISTRY_PROXY') }}"

skip_pingtest_cleanup: true
# Overcloud deploy
overcloud_templates_path: /usr/share/openstack-tripleo-heat-templates

# Network
# Deploy args
flavor_args: ""

deploy_timeout: 110

# Images settings
image_cache_dir: "{{ working_dir }}/images-cache"
image_cache_dir_cleanup: true
# user home (working_dir default) is the base dir for all images operations
# if it's changed, nothing will work
images_working_dir: "{{ working_dir }}"
build_image_isolated: false
build_undercloud: false
images_destroy_working_dir: false
libguestfs_mode: false
generate_pingtest_subunit: true
# Network settings
overcloud_dns_servers:
  - 10.1.8.10
  - 8.8.8.8
  - 8.8.4.4
step_adjust_mtu: true
mtu: 1350
host_network_interfaces:
  - eth0
  - eth1
  - "{% if network_isolation|default(true)|bool %}eth2{% endif %}"
mtu_interface: "{{ host_network_interfaces|select()|list }}"
floating_ip_cidr: >-
  {%- if network_isolation|default(true)|bool %}10.0.0.0/24
  {%- else %}192.168.24.0/24
  {%- endif %}
tempest_test_image_path: /opt/stack/cache/files/cirros-0.3.5-x86_64-disk.img
