heat_template_version: 2016-04-08

description: >
  OpenStack Core Service

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  Debug:
    type: string
    default: ''

resources:

outputs:
  role_data:
    description: Role data for the Keystone role.
    value:
      service_name: core
      config_settings:
          tripleo.core.firewall_rules:
            '999 core':
              proto: 'udp'
              dport:
                - 4789
