# TODO(bnemec): Should these settings be moved to low-memory-usage.yaml
# in tripleo-heat-templates?
parameter_defaults:
  controllerExtraConfig:
    heat::api_cloudwatch::enabled: false
    heat::api_cfn::enabled: false
    heat::rpc_response_timeout: 600
