# Collect logs settings

# artcl_tar_gz: true
artcl_gzip_only: true
artcl_txt_rename: true
artcl_publish: true
artcl_rsync_logs: false
artcl_collect_list:
  - /var/log/
  - /home/{{ undercloud_user }}/.instack/install-undercloud.log
  - /home/{{ undercloud_user }}/stackrc
  - /home/{{ undercloud_user }}/overcloudrc
  - /home/{{ undercloud_user }}/*.log
  - /home/{{ undercloud_user }}/*.txt
  - /home/{{ undercloud_user }}/*.json
  - /home/{{ undercloud_user }}/*.conf
  - /home/{{ undercloud_user }}/*.yml
  - /home/{{ undercloud_user }}/*.yaml
  - /home/{{ undercloud_user }}/*.sh
  - /home/{{ undercloud_user }}/deploy-overcloudrc
  - /home/{{ undercloud_user }}/network-environment.yaml
  - /home/{{ undercloud_user }}/skip_file
  - /home/{{ undercloud_user }}/*.subunit
  - /home/{{ undercloud_user }}/tempest/*.xml
  - /home/{{ undercloud_user }}/tempest/*.html
  - /home/{{ undercloud_user }}/tempest/*.log
  - /home/{{ undercloud_user }}/tempest/*.subunit
  - /home/{{ undercloud_user }}/tempest/*.sh
  - /home/{{ undercloud_user }}/tempest/etc/*.conf
  - /home/{{ undercloud_user }}/tempest/.testrepository/*
  - /home/{{ undercloud_user }}/local_tht/
  - /tmp/*.yml
  - /tmp/*.yaml
  - /etc/ansible/
  - /etc/aodh/
  - /etc/autofs*
  - /etc/auto.master*
  - /etc/barbican/
  - /etc/ceilometer/
  - /etc/centos-release*
  - /etc/ceph/
  - /etc/ci/
  - /etc/cinder/
  - /etc/cloud/
  - /etc/collectd.conf*
  - /etc/collectd.d/
  - /etc/congress/
  - /etc/containers/
  - /etc/corosync/
  - /etc/default/
  - /etc/dib-*/
  - /etc/dib-*
  - /etc/dnsmasq*
  - /etc/docker/
  - /etc/docker-distribution/
  - /etc/ec2api/
  - /etc/etcd/
  - /etc/exports*
  - /etc/exports*/
  - /etc/facter/
  - /etc/firewalld/
  - /etc/fluentd/
  - /etc/fstab
  - /etc/glance/
  - /etc/gnocchi/
  - /etc/group*
  - /etc/ha.d/
  - /etc/haproxy/
  - /etc/heat/
  - /etc/hiera.*
  - /etc/host.conf
  - /etc/hostname
  - /etc/hosts
  - /etc/httpd/conf*/
  - /etc/idmapd.conf
  - /etc/image-hostname
  - /etc/ipa/
  - /etc/iproute2/
  - /etc/ironic/
  - /etc/ironic-inspector/
  - /etc/iscsi/
  - /etc/keepalived/
  - /etc/keystone/
  - /etc/kolla/
  - /etc/krb5.conf*
  - /etc/krb5.conf*/
  - /etc/libvirt/
  - /etc/lsb-release.d/
  - /etc/lvm/
  - /etc/machine-id
  - /etc/manila/
  - /etc/mistral/
  - /etc/modprobe.d/
  - /etc/mongo*
  - /etc/my.cnf*
  - /etc/my.cnf.d/
  - /etc/networks*
  - /etc/neutron/
  - /etc/nodepool/
  - /etc/nova*
  - /etc/nova*/
  - /etc/nsswitch.conf*
  - /etc/ntp/
  - /etc/ntp.conf
  - /etc/numad.conf
  - /etc/oci-register-machine.conf
  - /etc/octavia/
  - /etc/openldap/
  - /etc/openstack-dashboard
  - /etc/openvswitch/
  - /etc/os-*
  - /etc/pacemaker/
  - /etc/panko/
  - /etc/pip.conf
  - /etc/pki/
  - /etc/polkit-1/
  - /etc/protocols*
  - /etc/puppet/
  - /etc/pycadf/
  - /etc/python/
  - /etc/qemu-kvm/
  - /etc/qpid-dispatch/
  - /etc/rabbitmq/
  - /etc/radvd.conf
  - /etc/redhat-lsb/
  - /etc/redhat-release*
  - /etc/redis*
  - /etc/redis*/
  - /etc/resolv.*
  - /etc/rootwrap.d/
  - /etc/rsyncd.conf
  - /etc/rsyslog.*
  - /etc/rsyslog.d/
  - /etc/ryu/
  - /etc/sahara/
  - /etc/sasl2/
  - /etc/security/
  - /etc/selinux/
  - /etc/sensu/
  - /etc/sestatus.conf
  - /etc/shadow*
  - /etc/snmp/
  - /etc/skydive/
  - /etc/sos.conf
  - /etc/ssl/
  - /etc/ssh/
  - /etc/sssd/
  - /etc/sudo.conf
  - /etc/sudoers*
  - /etc/swift/
  - /etc/sysconfig/
  - /etc/sysctl.*
  - /etc/sysctl.d/
  - /etc/systemd/
  - /etc/tacker/
  - /etc/target/
  - /etc/tempest/
  - /etc/trove/
  - /etc/trusted-*
  - /etc/tuna/
  - /etc/vconsole.conf
  - /etc/yum/
  - /etc/yum.conf
  - /etc/yum.repos.d/
  - /etc/zaqar/
  - /tmp/ansible*/
artcl_exclude_list:
  - /etc/puppet/modules/
  - /var/log/journal/*
  - /var/log/extra/lsof*
