# Collect logs settings

# artcl_tar_gz: true
artcl_gzip_only: true
artcl_txt_rename: true
artcl_publish: true
artcl_rsync_logs: false
artcl_collect_list:
  - /etc/
  - /var/log/
  - /home/{{ undercloud_user }}/.instack/install-undercloud.log
  - /home/{{ undercloud_user }}/stackrc
  - /home/{{ undercloud_user }}/overcloudrc
  - /home/{{ undercloud_user }}/*.log
  - /home/{{ undercloud_user }}/*.txt
  - /home/{{ undercloud_user }}/*.json
  - /home/{{ undercloud_user }}/*.conf
  - /home/{{ undercloud_user }}/*.yml
  - /home/{{ undercloud_user }}/*.yaml
  - /home/{{ undercloud_user }}/*.sh
  - /home/{{ undercloud_user }}/deploy-overcloudrc
  - /home/{{ undercloud_user }}/network-environment.yaml
  - /home/{{ undercloud_user }}/skip_file
  - /home/{{ undercloud_user }}/*.subunit
  - /home/{{ undercloud_user }}/tempest/*.xml
  - /home/{{ undercloud_user }}/tempest/*.html
  - /home/{{ undercloud_user }}/tempest/*.log
  - /home/{{ undercloud_user }}/tempest/*.subunit
  - /home/{{ undercloud_user }}/tempest/*.sh
  - /home/{{ undercloud_user }}/tempest/etc/*.conf
  - /home/{{ undercloud_user }}/local_tht/
  - /tmp/*.yml
  - /tmp/*.yaml
artcl_exclude_list:
  - /etc/asound.conf
  - /etc/at.deny
  - /etc/bash_completion.d/
  - /etc/bashrc
  - /etc/csh*
  - /etc/dbus-1
  - /etc/dhcp
  - /etc/DIR_COLORS*
  - /etc/favicon.png
  - /etc/fonts
  - /etc/GeoIP*
  - /etc/GREP_COLORS
  - /etc/grub*
  - /etc/ld.so.conf*
  - /etc/pam*
  - /etc/postfix*
  - /etc/pulse
  - /etc/samba*
  - /etc/X11
  - /etc/xinetd*
  - /etc/udev/hwdb.bin
  - /etc/puppet/modules
  - /etc/project-config
  - /etc/services
  - /etc/selinux/targeted
  - /etc/pki/ca-trust/extracted
  - /etc/alternatives
  - /var/log/extra/lsof*
